/** Curated Ionicons catalog for the task/habit icon picker, grouped by theme. */

export interface IconGroup {
  label: string;
  icons: string[];
}

export const ICON_GROUPS: IconGroup[] = [
  {
    label: 'General',
    icons: [
      'ellipse-outline',
      'star-outline',
      'flag-outline',
      'checkmark-circle-outline',
      'list-outline',
      'calendar-outline',
      'time-outline',
      'alarm-outline',
      'bookmark-outline',
      'pin-outline',
      'bulb-outline',
      'rocket-outline',
    ],
  },
  {
    label: 'Work & Study',
    icons: [
      'briefcase-outline',
      'laptop-outline',
      'desktop-outline',
      'code-slash-outline',
      'terminal-outline',
      'mail-outline',
      'call-outline',
      'people-outline',
      'videocam-outline',
      'document-text-outline',
      'folder-outline',
      'school-outline',
      'book-outline',
      'library-outline',
      'pencil-outline',
      'calculator-outline',
      'newspaper-outline',
      'mic-outline',
    ],
  },
  {
    label: 'Health & Fitness',
    icons: [
      'barbell-outline',
      'bicycle-outline',
      'walk-outline',
      'fitness-outline',
      'heart-outline',
      'pulse-outline',
      'body-outline',
      'medkit-outline',
      'bandage-outline',
      'bed-outline',
      'moon-outline',
      'water-outline',
      'nutrition-outline',
      'leaf-outline',
      'flower-outline',
      'football-outline',
      'basketball-outline',
      'tennisball-outline',
    ],
  },
  {
    label: 'Food & Home',
    icons: [
      'restaurant-outline',
      'cafe-outline',
      'pizza-outline',
      'fast-food-outline',
      'wine-outline',
      'beer-outline',
      'ice-cream-outline',
      'home-outline',
      'bed-outline',
      'cart-outline',
      'basket-outline',
      'shirt-outline',
      'cut-outline',
      'hammer-outline',
      'construct-outline',
      'trash-outline',
      'paw-outline',
      'key-outline',
    ],
  },
  {
    label: 'Leisure & Travel',
    icons: [
      'game-controller-outline',
      'musical-notes-outline',
      'headset-outline',
      'film-outline',
      'tv-outline',
      'camera-outline',
      'color-palette-outline',
      'brush-outline',
      'gift-outline',
      'balloon-outline',
      'airplane-outline',
      'car-outline',
      'bus-outline',
      'train-outline',
      'boat-outline',
      'map-outline',
      'compass-outline',
      'earth-outline',
      'sunny-outline',
      'umbrella-outline',
    ],
  },
  {
    label: 'Money & Misc',
    icons: [
      'card-outline',
      'cash-outline',
      'wallet-outline',
      'trending-up-outline',
      'stats-chart-outline',
      'pie-chart-outline',
      'phone-portrait-outline',
      'battery-charging-outline',
      'cloud-outline',
      'sparkles-outline',
      'flash-outline',
      'flame-outline',
      'snow-outline',
      'planet-outline',
      'infinite-outline',
      'happy-outline',
      'chatbubbles-outline',
      'notifications-outline',
    ],
  },
];

export const ALL_ICONS: string[] = ICON_GROUPS.flatMap((g) => g.icons);
